name: Build Status

on:
  push:
    paths:
      - "src/execute_*.cpp"
  pull_request:
    paths:
      - "src/execute_*.cpp"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on:
      group: k23a
    strategy:
      matrix:
        impl: [default]

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: |
          cmake -S . -B build-${{ matrix.impl }} -DEXECUTE_IMPL=${{ matrix.impl }} -DCMAKE_BUILD_TYPE=Release -Wno-dev

      - name: Build
        run: |
          cmake --build build-${{ matrix.impl }} --target software_tester -- -j

      - name: Run software tests
        run: |
          ./build-${{ matrix.impl }}/software_tester --reporter compact
